apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground
  namespace: dev
  labels:
    app: will-playground
spec:
  selector:
    matchLabels:
      app: will-playground
  template:
    metadata:
      labels:
        app: will-playground
    spec:
      containers:
      - name: will-playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: will-playground
  namespace: dev
  labels:
    app: will-playground
spec:
  type: NodePort
  selector:
    app: will-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088
